### ISSUE TITLE
7.4.2. 피쳐 엔지니어링 2: 피쳐 스케일링, Data Leakage 문제 발생가능성?

### ISSUE THREAD

**Issue by shashashak** [BaekKyunShin/musthave_mldl_problem_solving_strategy#1]
우선 좋은 책 써주신 점 감사드립니다. 

질문을 드리고 싶은 지점은 Scaling과 Data Leakage의 관련성입니다. 

특히 287쪽 #min-max 정규화 부분(7.4.2)
`all_data[ord_features] = MinMaxScaler().fit_transform(all_data[ord_features])
`
train, test set를 합친 all_data에 대하여 minmax 스케일링을 적용하셨는데, 이러면 data leakage 문제가 발생하지 않을까요? 물론 이 문제가 모델에서 중요한가, 안 중요한가는 별개의 문제지만요. 

더욱이 Scaling을 적용한다면, GridSearchCV에서 Cross Validation을 할 때도 Validation set을 제외한 Training Set에 대해서만 스케일링을 적용하는 코드가 추가로 필요할 것 같습니다. 혹시 어떻게 생각하시는지여쭙고자 글을 올렸습니다

**Comment by BaekKyunShin** [comment]
안녕하십니까.
저자 신백균입니다.

좋은 질문주셔서 감사드립니다.

변환을 적용하는 방법은 다음과 같이 두 가지입니다.
1) 훈련 데이터로 fit을 한 뒤, 훈련 데이터, 테스트 데이터에 transform 적용
2) 훈련 데이터와 테스트 데이터를 결합한 뒤 fit을 한 뒤, 훈련 데이터, 테스트 데이터 transform 적용

책에서는 2번 방법이 쓰였습니다.
물론 실무에서는 테스트 데이터가 당장 없으므로 1번 방법을 써야겠지요.
말씀하신 대로 2번 방법으로 적용하면 Data Leakage라고 볼 수도 있습니다.
간혹 데이콘에서 여는 경진대회에서는 엄격하게 판단해 2번 방법으로 스케일링을 적용하면 Data Leakage로 간주해 실격이 되는 경우도 있다고
합니다.

하지만, 처음부터 테스트 데이터가 주어진 상황에서는 2번 방법을 적극 활용해볼 수 있습니다.
1번 방법을 적용하면 훈련 데이터에만 과적합되어 일반화 성능이 떨어질 수 있다는 단점도 있습니다.

1번 방법과 2번 방법 모두 각자의 장단점이 있고, 어떤 입장을 견지하냐에 따라 생각을 달리할 수 있습니다.

결론은 엄격한 관점에서는 (Data Leakage를 피해기 위해) 1번 방법을 적용해야 합니다.
그렇지만 테스트 데이터를 처음부터 활용할 수 있는 상황에서는 큰 제약조건이 없는 한 2번 방법을 적극 활용할 수 있습니다.
훈련 데이터와 테스트 데이터의 분산이 크게 차이 나지 않는 이상 1번, 2번의 결과 차이는 크지 않으니, 책에서는 '엄밀함'과 '편의성'의 trade off 중 '편의성'을 택한 것입니다. 

다시 한번 좋은 질문 주셔서 감사합니다.

2022년 11월 9일 (수) 오후 5:24, shashashak ***@***.***>님이 작성:
